[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mentor-app"
version = "0.1.0"
description = "Mentor app package"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["app*" ]
