# Railway configuration for deployment
# Ensure JWT_SECRET is set in Railway environment variables before deploying
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python production_backend.py"

[env]
NIXPACKS_PYTHON_VERSION = "3.11"
