# Stub for optional dependency 'librosa'
from typing import Any

def load(path: Any, sr: int | None = None, mono: bool | None = None) -> tuple[Any, int]: ...

def to_mono(y: Any) -> Any: ...

def resample(y: Any, orig_sr: int, target_sr: int) -> Any: ...

class feature:
    @staticmethod
    def mfcc(y: Any, sr: int, n_mfcc: int = 13) -> Any: ...
