# Safe defaults for first production cohort
DRY_RUN_AUTOMATIONS: true
ENABLE_AUTO_STEALTH: true
STRICT_RAG_BOUNDING: true
ALLOW_SCREEN_RECORDING: false
DEFAULT_RETENTION_DAYS:
  RAW_VIDEO: 7
  TRANSCRIPTS: 30
  VECTORS: 180
RATE_LIMITS:
  MEETING_EVENTS_PER_MIN: 600
  ANSWERS_PER_MIN: 30
COST_LIMITS:
  TOKENS_PER_DAY: 250000
  WARN_AT: 0.8
